name: Download Public Docker Image

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  download-docker-image:
    runs-on: ubuntu-latest

    steps:
      # 检出代码（如果需要）
      - name: Checkout Code
        uses: actions/checkout@v3

      # 安装 Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 下载指定的 Docker 镜像
      - name: Pull Docker Image
        run: |
          docker pull wordpress:latest

      # 可选：保存镜像为 tar 文件
      - name: Save Docker Image as Tar
        run: |
          docker save -o wordpress.tar wordpress:latest

      # 使用最新版本上传 Artifact
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-docker-image
          path: ./wordpress.tar
