name: Download Public Docker Image

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  download-docker-image:
    runs-on: ubuntu-latest

    steps:
      # 安装 Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 下载指定的 Docker 镜像
      - name: Pull Docker Image
        run: |
          docker pull wordpress:6.7.2-php8.2-fpm

      # 可选：保存镜像为 tar 文件
      - name: Save Docker Image as Tar
        run: |
          docker save -o wordpress.tar wordpress:6.7.2-php8.2-fpm

      # 可选：上传镜像作为工作流 Artifact
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-docker-image
          path: ./wordpress.tar
